export const proxyContractAbi = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  { inputs: [{ internalType: 'uint32', name: 'version', type: 'uint32' }], name: 'AlreadyInitialized', type: 'error' },
  {
    inputs: [
      { internalType: 'string', name: 'domain', type: 'string' },
      { internalType: 'string', name: 'domainSuffix', type: 'string' },
    ],
    name: 'DomainAlreadyRegistered',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'string', name: 'domain', type: 'string' },
      { internalType: 'string', name: 'domainSuffix', type: 'string' },
    ],
    name: 'DomainNotRegistered',
    type: 'error',
  },
  { inputs: [{ internalType: 'string', name: 'name', type: 'string' }], name: 'EnsIdentityIsExpired', type: 'error' },
  {
    inputs: [
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'FailedToSendEther',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'value', type: 'uint256' },
      { internalType: 'uint256', name: 'requiredValue', type: 'uint256' },
    ],
    name: 'InsufficientFunds',
    type: 'error',
  },
  { inputs: [{ internalType: 'address', name: 'addr', type: 'address' }], name: 'InvalidAddress', type: 'error' },
  { inputs: [], name: 'InvalidDelegate', type: 'error' },
  { inputs: [], name: 'InvalidDuration', type: 'error' },
  { inputs: [], name: 'InvalidEndpointCall', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'given', type: 'uint256' },
      { internalType: 'uint256', name: 'userNonce', type: 'uint256' },
    ],
    name: 'InvalidNonce',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint32', name: 'srcEid', type: 'uint32' },
      { internalType: 'uint32', name: 'dstEid', type: 'uint32' },
    ],
    name: 'InvalidOrigin',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'string', name: 'domain', type: 'string' },
      { internalType: 'string', name: 'domainSuffix', type: 'string' },
      { internalType: 'uint256', name: 'price', type: 'uint256' },
      { internalType: 'uint256', name: 'msgValue', type: 'uint256' },
    ],
    name: 'InvalidPriceOrFunds',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'string', name: 'key', type: 'string' },
      { internalType: 'string', name: 'value', type: 'string' },
    ],
    name: 'InvalidRecord',
    type: 'error',
  },
  { inputs: [], name: 'InvalidRecords', type: 'error' },
  { inputs: [], name: 'InvalidSignature', type: 'error' },
  { inputs: [{ internalType: 'string', name: 'to', type: 'string' }], name: 'InvalidToAddress', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'value', type: 'uint256' },
      { internalType: 'uint256', name: 'minOrExpected', type: 'uint256' },
    ],
    name: 'InvalidValue',
    type: 'error',
  },
  { inputs: [], name: 'LzTokenUnavailable', type: 'error' },
  { inputs: [{ internalType: 'string', name: 'name', type: 'string' }], name: 'NameIsExclusive', type: 'error' },
  { inputs: [{ internalType: 'uint32', name: 'eid', type: 'uint32' }], name: 'NoPeer', type: 'error' },
  { inputs: [{ internalType: 'uint256', name: 'msgValue', type: 'uint256' }], name: 'NotEnoughNative', type: 'error' },
  {
    inputs: [
      { internalType: 'string', name: 'domain', type: 'string' },
      { internalType: 'string', name: 'domainSuffix', type: 'string' },
      { internalType: 'address', name: 'user', type: 'address' },
    ],
    name: 'NotOwnerOf',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'address', name: 'user', type: 'address' },
    ],
    name: 'NotOwnerOfEnsName',
    type: 'error',
  },
  { inputs: [{ internalType: 'address', name: 'addr', type: 'address' }], name: 'OnlyEndpoint', type: 'error' },
  {
    inputs: [
      { internalType: 'uint32', name: 'eid', type: 'uint32' },
      { internalType: 'bytes32', name: 'sender', type: 'bytes32' },
    ],
    name: 'OnlyPeer',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'string', name: 'domain', type: 'string' },
      { internalType: 'string', name: 'domainSuffix', type: 'string' },
      { internalType: 'bytes4', name: 'orderType', type: 'bytes4' },
    ],
    name: 'OperationStillPending',
    type: 'error',
  },
  { inputs: [], name: 'OrderAlreadyProcessed', type: 'error' },
  { inputs: [], name: 'OrderStillPending', type: 'error' },
  { inputs: [{ internalType: 'address', name: 'owner', type: 'address' }], name: 'OwnableInvalidOwner', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  { inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'address', name: 'user', type: 'address' },
    ],
    name: 'UserIsNotOwnerOfName',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'withdrawAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'totalFees', type: 'uint256' },
    ],
    name: 'WithdrawalAmountExceedsTotalFees',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'bytes4', name: 'orderType', type: 'bytes4' },
      { indexed: false, internalType: 'uint256', name: 'nonce', type: 'uint256' },
      { indexed: false, internalType: 'bytes', name: 'payload', type: 'bytes' },
    ],
    name: 'LZOrderCallbackReceived',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'bytes4', name: 'orderType', type: 'bytes4' },
      { indexed: false, internalType: 'uint256', name: 'nonce', type: 'uint256' },
      { indexed: false, internalType: 'bytes', name: 'payload', type: 'bytes' },
    ],
    name: 'LZOrderSent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'nonce', type: 'uint256' },
    ],
    name: 'OrderWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint32', name: 'eid', type: 'uint32' },
      { indexed: false, internalType: 'bytes32', name: 'peer', type: 'bytes32' },
    ],
    name: 'PeerSet',
    type: 'event',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint32', name: 'srcEid', type: 'uint32' },
          { internalType: 'bytes32', name: 'sender', type: 'bytes32' },
          { internalType: 'uint64', name: 'nonce', type: 'uint64' },
        ],
        internalType: 'struct Origin',
        name: 'origin',
        type: 'tuple',
      },
    ],
    name: 'allowInitializePath',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_name', type: 'string' },
      { internalType: 'address', name: '_user', type: 'address' },
    ],
    name: 'canClaimEnsIdentity',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_name', type: 'string' },
      { internalType: 'bytes', name: '_options', type: 'bytes' },
      { internalType: 'bytes', name: '_pythUpdateData', type: 'bytes' },
    ],
    name: 'claimEnsIdentity',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'desiredPendingDuration',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'dstEid',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'endpoint',
    outputs: [{ internalType: 'contract ILayerZeroEndpointV2', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: '_name', type: 'string' }],
    name: 'getAvatarIpfsHash',
    outputs: [{ internalType: 'string', name: 'avatar', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'uint256', name: '_nonce', type: 'uint256' },
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_avatar', type: 'string' },
      { internalType: 'uint64', name: '_duration', type: 'uint64' },
      { internalType: 'uint256', name: '_price', type: 'uint256' },
      { internalType: 'uint256', name: '_priceUsd', type: 'uint256' },
    ],
    name: 'getClaimEnsIdentityPayload',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: '_name', type: 'string' }],
    name: 'getEnsData',
    outputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'address', name: 'resolver', type: 'address' },
      { internalType: 'uint64', name: 'expiry', type: 'uint64' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: '_name', type: 'string' }],
    name: 'getExpiration',
    outputs: [{ internalType: 'uint64', name: 'expiry', type: 'uint64' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'uint256', name: '_nonce', type: 'uint256' },
      { internalType: 'bytes', name: '_signature', type: 'bytes' },
      { internalType: 'bytes32', name: '_pubkey', type: 'bytes32' },
      { internalType: 'uint64', name: '_deadline', type: 'uint64' },
    ],
    name: 'getLinkToAAPayload',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: '_name', type: 'string' }],
    name: 'getOwner',
    outputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'uint256', name: '_nonce', type: 'uint256' },
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_domainSuffix', type: 'string' },
      { internalType: 'uint64', name: '_duration', type: 'uint64' },
      { internalType: 'uint256', name: '_price', type: 'uint256' },
      { internalType: 'uint256', name: '_usdPrice', type: 'uint256' },
      { internalType: 'string', name: '_voucherId', type: 'string' },
      { internalType: 'bytes32[]', name: '_merkleProof', type: 'bytes32[]' },
    ],
    name: 'getRegisterDomainPayload',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'uint256', name: '_nonce', type: 'uint256' },
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_domainSuffix', type: 'string' },
      { internalType: 'uint64', name: '_renewalDuration', type: 'uint64' },
      { internalType: 'uint256', name: '_price', type: 'uint256' },
      { internalType: 'uint256', name: '_usdPrice', type: 'uint256' },
    ],
    name: 'getRenewDomainPayload',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: '_name', type: 'string' }],
    name: 'getResolver',
    outputs: [{ internalType: 'address', name: 'resolver', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'uint256', name: '_nonce', type: 'uint256' },
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_domainSuffix', type: 'string' },
      { internalType: 'string', name: '_avatarIpfsHash', type: 'string' },
    ],
    name: 'getSetAvatarIpfsHashPayload',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'uint256', name: '_nonce', type: 'uint256' },
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_domainSuffix', type: 'string' },
    ],
    name: 'getSetPrimaryNamePayload',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'uint256', name: '_nonce', type: 'uint256' },
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_domainSuffix', type: 'string' },
      { internalType: 'string[]', name: '_caips', type: 'string[]' },
      { internalType: 'string[]', name: '_addresses', type: 'string[]' },
      { internalType: 'string[]', name: '_keys', type: 'string[]' },
      { internalType: 'string[]', name: '_values', type: 'string[]' },
    ],
    name: 'getSetRecordsPayload',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'uint256', name: '_nonce', type: 'uint256' },
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_domainSuffix', type: 'string' },
      { internalType: 'string', name: '_to', type: 'string' },
    ],
    name: 'getTransferDomainPayload',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_endpoint', type: 'address' },
      { internalType: 'address', name: '_owner', type: 'address' },
      { internalType: 'address', name: '_priceModel', type: 'address' },
      { internalType: 'uint32', name: '_dstEid', type: 'uint32' },
      { internalType: 'string', name: '_caip', type: 'string' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_ensRegistry', type: 'address' }],
    name: 'initializeENS',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'initializedVersion',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint32', name: 'srcEid', type: 'uint32' },
          { internalType: 'bytes32', name: 'sender', type: 'bytes32' },
          { internalType: 'uint64', name: 'nonce', type: 'uint64' },
        ],
        internalType: 'struct Origin',
        name: '',
        type: 'tuple',
      },
      { internalType: 'bytes', name: '', type: 'bytes' },
      { internalType: 'address', name: '_sender', type: 'address' },
    ],
    name: 'isComposeMsgSender',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes', name: '_moveWalletSignature', type: 'bytes' },
      { internalType: 'bytes32', name: '_moveWalletPubkey', type: 'bytes32' },
      { internalType: 'uint64', name: '_deadline', type: 'uint64' },
      { internalType: 'bytes', name: '_options', type: 'bytes' },
    ],
    name: 'linkToMoveAA',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint32', name: 'srcEid', type: 'uint32' },
          { internalType: 'bytes32', name: 'sender', type: 'bytes32' },
          { internalType: 'uint64', name: 'nonce', type: 'uint64' },
        ],
        internalType: 'struct Origin',
        name: '_origin',
        type: 'tuple',
      },
      { internalType: 'bytes32', name: '_guid', type: 'bytes32' },
      { internalType: 'bytes', name: '_message', type: 'bytes' },
      { internalType: 'address', name: '_executor', type: 'address' },
      { internalType: 'bytes', name: '_extraData', type: 'bytes' },
    ],
    name: 'lzReceive',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: '_newSSOT', type: 'bytes32' },
      { internalType: 'uint32', name: '_dstEid', type: 'uint32' },
    ],
    name: 'migrateSSOT',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint32', name: '', type: 'uint32' },
      { internalType: 'bytes32', name: '', type: 'bytes32' },
    ],
    name: 'nextNonce',
    outputs: [{ internalType: 'uint64', name: 'nonce', type: 'uint64' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'oAppVersion',
    outputs: [
      { internalType: 'uint64', name: 'senderVersion', type: 'uint64' },
      { internalType: 'uint64', name: 'receiverVersion', type: 'uint64' },
    ],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: 'eid', type: 'uint32' }],
    name: 'peers',
    outputs: [{ internalType: 'bytes32', name: 'peer', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'priceModel',
    outputs: [{ internalType: 'contract IPriceModel', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes', name: '_payload', type: 'bytes' },
      { internalType: 'bytes', name: '_options', type: 'bytes' },
    ],
    name: 'quoteFee',
    outputs: [
      { internalType: 'uint256', name: 'nativeFee', type: 'uint256' },
      { internalType: 'uint256', name: 'zroFee', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_domainSuffix', type: 'string' },
      { internalType: 'uint64', name: '_duration', type: 'uint64' },
      { internalType: 'bytes', name: '_options', type: 'bytes' },
      { internalType: 'bytes', name: '_pythUpdateData', type: 'bytes' },
    ],
    name: 'registerDomain',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'string', name: 'domain', type: 'string' },
          { internalType: 'string', name: 'domainSuffix', type: 'string' },
          { internalType: 'uint64', name: 'duration', type: 'uint64' },
          { internalType: 'bytes', name: 'options', type: 'bytes' },
          { internalType: 'bytes', name: 'pythUpdateData', type: 'bytes' },
          { internalType: 'string', name: 'voucherId', type: 'string' },
          { internalType: 'bytes32[]', name: 'merkleProof', type: 'bytes32[]' },
        ],
        internalType: 'struct IEvmProxy.RegisterDomainWithVoucherData',
        name: '_calldata',
        type: 'tuple',
      },
    ],
    name: 'registerDomainWithVoucher',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_domainSuffix', type: 'string' },
      { internalType: 'uint64', name: '_renewalDuration', type: 'uint64' },
      { internalType: 'bytes', name: '_options', type: 'bytes' },
      { internalType: 'bytes', name: '_pythUpdateData', type: 'bytes' },
    ],
    name: 'renewDomain',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [{ internalType: 'address', name: '_delegate', type: 'address' }],
    name: 'setDelegate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_duration', type: 'uint256' }],
    name: 'setDesiredPendingDuration',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_domainSuffix', type: 'string' },
      { internalType: 'string', name: 'avatarIpfsHash', type: 'string' },
      { internalType: 'bytes', name: '_options', type: 'bytes' },
    ],
    name: 'setIpfsHash',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint32', name: '', type: 'uint32' },
      { internalType: 'bytes32', name: '', type: 'bytes32' },
    ],
    name: 'setPeer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_priceModel', type: 'address' }],
    name: 'setPriceModel',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_domainSuffix', type: 'string' },
      { internalType: 'bytes', name: '_options', type: 'bytes' },
    ],
    name: 'setPrimaryName',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_domainSuffix', type: 'string' },
      { internalType: 'string[]', name: '_caips', type: 'string[]' },
      { internalType: 'string[]', name: '_addresses', type: 'string[]' },
      { internalType: 'string[]', name: '_keys', type: 'string[]' },
      { internalType: 'string[]', name: '_values', type: 'string[]' },
      { internalType: 'bytes', name: '_options', type: 'bytes' },
    ],
    name: 'setRecords',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalFees',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_domain', type: 'string' },
      { internalType: 'string', name: '_domainSuffix', type: 'string' },
      { internalType: 'string', name: '_to', type: 'string' },
      { internalType: 'bytes', name: '_options', type: 'bytes' },
    ],
    name: 'transferDomain',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint256', name: '_value', type: 'uint256' },
    ],
    name: 'withdrawFee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'uint256', name: '_nonce', type: 'uint256' },
    ],
    name: 'withdrawOrder',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const
